language: node_js
node_js:
  - "10"

script:
  - npm run eclint
  - npm run eslint
  - npm test

deploy:
  local-dir: dist
  repo: imhofjs/imhofjs.github.io
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
